// Autogenerated by generate_hilbert_tables.cpp
// Tables for alternative Hilbert child geometry (2D..7D).

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

static const uint8_t HILBERT_GRAY_2[4] = {
  0, 2, 3, 1
};

static const uint8_t HILBERT_GRAY_RANK_2[4] = {
  0, 3, 1, 2
};

static const uint8_t HILBERT_CHILD_ENTRY_2[4] = {
  0, 0, 0, 3
};

static const uint8_t HILBERT_CHILD_DIR_2[4] = {
  1, 0, 0, 1
};

static const uint8_t HILBERT_GRAY_3[8] = {
  0, 2, 6, 4, 5, 7, 3, 1
};

static const uint8_t HILBERT_GRAY_RANK_3[8] = {
  0, 7, 1, 6, 3, 4, 2, 5
};

static const uint8_t HILBERT_CHILD_ENTRY_3[8] = {
  0, 0, 0, 3, 0, 0, 5, 3
};

static const uint8_t HILBERT_CHILD_DIR_3[8] = {
  1, 2, 0, 1, 1, 0, 2, 1
};

static const uint8_t HILBERT_GRAY_4[16] = {
  0, 2, 6, 4, 12, 14, 10, 8, 9, 11, 15, 13, 5, 7, 3, 1
};

static const uint8_t HILBERT_GRAY_RANK_4[16] = {
  0, 15, 1, 14, 3, 12, 2, 13, 7, 8, 6, 9, 4, 11, 5, 10
};

static const uint8_t HILBERT_CHILD_ENTRY_4[16] = {
  0, 0, 0, 3, 3, 0, 5, 6, 6, 5, 0, 3, 10, 9, 5, 3
};

static const uint8_t HILBERT_CHILD_DIR_4[16] = {
  1, 2, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 2, 1
};

static const uint8_t HILBERT_GRAY_5[32] = {
  0, 2, 6, 4, 12, 14, 10, 8, 24, 26, 30, 28, 20, 22, 18, 16, 
  17, 19, 23, 21, 29, 31, 27, 25, 9, 11, 15, 13, 5, 7, 3, 1
};

static const uint8_t HILBERT_GRAY_RANK_5[32] = {
  0, 31, 1, 30, 3, 28, 2, 29, 7, 24, 6, 25, 4, 27, 5, 26, 
  15, 16, 14, 17, 12, 19, 13, 18, 8, 23, 9, 22, 11, 20, 10, 21
};

static const uint8_t HILBERT_CHILD_ENTRY_5[32] = {
  0, 0, 0, 3, 3, 0, 5, 6, 6, 5, 0, 3, 10, 9, 12, 15, 
  12, 12, 9, 10, 3, 0, 5, 6, 23, 20, 17, 18, 27, 17, 5, 3
};

static const uint8_t HILBERT_CHILD_DIR_5[32] = {
  1, 2, 0, 3, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 
  1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 2, 1
};

static const uint8_t HILBERT_GRAY_6[64] = {
  0, 2, 6, 4, 12, 14, 10, 8, 24, 26, 30, 28, 20, 22, 18, 16, 
  48, 50, 54, 52, 60, 62, 58, 56, 40, 42, 46, 44, 36, 38, 34, 32, 
  33, 35, 39, 37, 45, 47, 43, 41, 57, 59, 63, 61, 53, 55, 51, 49, 
  17, 19, 23, 21, 29, 31, 27, 25, 9, 11, 15, 13, 5, 7, 3, 1
};

static const uint8_t HILBERT_GRAY_RANK_6[64] = {
  0, 63, 1, 62, 3, 60, 2, 61, 7, 56, 6, 57, 4, 59, 5, 58, 
  15, 48, 14, 49, 12, 51, 13, 50, 8, 55, 9, 54, 11, 52, 10, 53, 
  31, 32, 30, 33, 28, 35, 29, 34, 24, 39, 25, 38, 27, 36, 26, 37, 
  16, 47, 17, 46, 19, 44, 18, 45, 23, 40, 22, 41, 20, 43, 21, 42
};

static const uint8_t HILBERT_CHILD_ENTRY_6[64] = {
  0, 0, 0, 3, 3, 0, 5, 6, 6, 5, 0, 3, 10, 9, 12, 15, 
  15, 12, 9, 10, 3, 0, 5, 6, 23, 20, 17, 18, 27, 24, 29, 30, 
  30, 29, 24, 27, 18, 17, 20, 23, 6, 5, 0, 3, 10, 9, 12, 15, 
  46, 45, 40, 43, 34, 33, 36, 39, 54, 53, 48, 51, 43, 33, 5, 3
};

static const uint8_t HILBERT_CHILD_DIR_6[64] = {
  1, 2, 0, 3, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 5, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 3, 5, 2, 1
};

static const uint8_t HILBERT_GRAY_7[128] = {
  0, 2, 6, 4, 12, 14, 10, 8, 24, 26, 30, 28, 20, 22, 18, 16, 
  48, 50, 54, 52, 60, 62, 58, 56, 40, 42, 46, 44, 36, 38, 34, 32, 
  96, 98, 102, 100, 108, 110, 106, 104, 120, 122, 126, 124, 116, 118, 114, 112, 
  80, 82, 86, 84, 92, 94, 90, 88, 72, 74, 78, 76, 68, 70, 66, 64, 
  65, 67, 71, 69, 77, 79, 75, 73, 89, 91, 95, 93, 85, 87, 83, 81, 
  113, 115, 119, 117, 125, 127, 123, 121, 105, 107, 111, 109, 101, 103, 99, 97, 
  33, 35, 39, 37, 45, 47, 43, 41, 57, 59, 63, 61, 53, 55, 51, 49, 
  17, 19, 23, 21, 29, 31, 27, 25, 9, 11, 15, 13, 5, 7, 3, 1
};

static const uint8_t HILBERT_GRAY_RANK_7[128] = {
  0, 127, 1, 126, 3, 124, 2, 125, 7, 120, 6, 121, 4, 123, 5, 122, 
  15, 112, 14, 113, 12, 115, 13, 114, 8, 119, 9, 118, 11, 116, 10, 117, 
  31, 96, 30, 97, 28, 99, 29, 98, 24, 103, 25, 102, 27, 100, 26, 101, 
  16, 111, 17, 110, 19, 108, 18, 109, 23, 104, 22, 105, 20, 107, 21, 106, 
  63, 64, 62, 65, 60, 67, 61, 66, 56, 71, 57, 70, 59, 68, 58, 69, 
  48, 79, 49, 78, 51, 76, 50, 77, 55, 72, 54, 73, 52, 75, 53, 74, 
  32, 95, 33, 94, 35, 92, 34, 93, 39, 88, 38, 89, 36, 91, 37, 90, 
  47, 80, 46, 81, 44, 83, 45, 82, 40, 87, 41, 86, 43, 84, 42, 85
};

static const uint8_t HILBERT_CHILD_ENTRY_7[128] = {
  0, 0, 0, 3, 3, 0, 5, 6, 6, 5, 0, 3, 10, 9, 12, 15, 
  15, 12, 9, 10, 3, 0, 5, 6, 23, 20, 17, 18, 27, 24, 29, 30, 
  30, 29, 24, 27, 18, 17, 20, 23, 6, 5, 0, 3, 10, 9, 12, 15, 
  46, 45, 40, 43, 34, 33, 36, 39, 54, 53, 48, 51, 58, 57, 60, 63, 
  60, 60, 57, 58, 51, 48, 53, 54, 39, 36, 33, 34, 43, 40, 45, 46, 
  15, 12, 9, 10, 3, 0, 5, 6, 23, 20, 17, 18, 27, 24, 29, 30, 
  95, 92, 89, 90, 83, 80, 85, 86, 71, 68, 65, 66, 75, 72, 77, 78, 
  111, 108, 105, 106, 99, 96, 101, 102, 119, 116, 113, 99, 75, 65, 5, 3
};

static const uint8_t HILBERT_CHILD_DIR_7[128] = {
  1, 2, 0, 3, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 5, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
  1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5, 3, 6, 2, 1
};

static inline uint8_t hilbert_gray(uint32_t k, uint32_t w) {
  switch(k) {
    case 2: return HILBERT_GRAY_2[w];
    case 3: return HILBERT_GRAY_3[w];
    case 4: return HILBERT_GRAY_4[w];
    case 5: return HILBERT_GRAY_5[w];
    case 6: return HILBERT_GRAY_6[w];
    case 7: return HILBERT_GRAY_7[w];
    default: return 0;
  }
}

static inline uint8_t hilbert_gray_rank(uint32_t k, uint32_t g) {
  switch(k) {
    case 2: return HILBERT_GRAY_RANK_2[g];
    case 3: return HILBERT_GRAY_RANK_3[g];
    case 4: return HILBERT_GRAY_RANK_4[g];
    case 5: return HILBERT_GRAY_RANK_5[g];
    case 6: return HILBERT_GRAY_RANK_6[g];
    case 7: return HILBERT_GRAY_RANK_7[g];
    default: return 0;
  }
}

static inline uint8_t hilbert_child_entry(uint32_t k, uint32_t w) {
  switch(k) {
    case 2: return HILBERT_CHILD_ENTRY_2[w];
    case 3: return HILBERT_CHILD_ENTRY_3[w];
    case 4: return HILBERT_CHILD_ENTRY_4[w];
    case 5: return HILBERT_CHILD_ENTRY_5[w];
    case 6: return HILBERT_CHILD_ENTRY_6[w];
    case 7: return HILBERT_CHILD_ENTRY_7[w];
    default: return 0;
  }
}

static inline uint8_t hilbert_child_dir(uint32_t k, uint32_t w) {
  switch(k) {
    case 2: return HILBERT_CHILD_DIR_2[w];
    case 3: return HILBERT_CHILD_DIR_3[w];
    case 4: return HILBERT_CHILD_DIR_4[w];
    case 5: return HILBERT_CHILD_DIR_5[w];
    case 6: return HILBERT_CHILD_DIR_6[w];
    case 7: return HILBERT_CHILD_DIR_7[w];
    default: return 0;
  }
}

#ifdef __cplusplus
}
#endif
