// Autogenerated by generate_hilbert_tables.cpp
// Tables for Hilbert child geometry (1D..7D).

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

static const uint8_t HILBERT_GRAY_1[2] = {
  0, 1
};

static const uint8_t HILBERT_GRAY_RANK_1[2] = {
  0, 1
};

static const uint8_t HILBERT_CHILD_ENTRY_1[2] = {
  0, 0
};

static const uint8_t HILBERT_CHILD_DIR_1[2] = {
  0, 0
};

static const uint8_t HILBERT_GRAY_2[4] = {
  0, 2, 3, 1
};

static const uint8_t HILBERT_GRAY_RANK_2[4] = {
  0, 3, 1, 2
};

static const uint8_t HILBERT_CHILD_ENTRY_2[4] = {
  0, 0, 0, 3
};

static const uint8_t HILBERT_CHILD_DIR_2[4] = {
  1, 0, 0, 1
};

static const uint8_t HILBERT_GRAY_3[8] = {
  0, 2, 6, 4, 5, 7, 3, 1
};

static const uint8_t HILBERT_GRAY_RANK_3[8] = {
  0, 7, 1, 6, 3, 4, 2, 5
};

static const uint8_t HILBERT_CHILD_ENTRY_3[8] = {
  0, 0, 0, 3, 0, 0, 5, 3
};

static const uint8_t HILBERT_CHILD_DIR_3[8] = {
  1, 2, 0, 1, 1, 0, 2, 1
};

static const uint8_t HILBERT_GRAY_4[16] = {
  0, 8, 10, 2, 6, 4, 12, 14, 15, 7, 3, 11, 9, 13, 5, 1
};

static const uint8_t HILBERT_GRAY_RANK_4[16] = {
  0, 15, 3, 10, 5, 14, 4, 9, 1, 12, 2, 11, 6, 13, 7, 8
};

static const uint8_t HILBERT_CHILD_ENTRY_4[16] = {
  0, 0, 0, 9, 9, 10, 3, 0, 0, 9, 12, 5, 6, 3, 9, 5
};

static const uint8_t HILBERT_CHILD_DIR_4[16] = {
  3, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 2
};

static const uint8_t HILBERT_GRAY_5[32] = {
  0, 2, 10, 8, 12, 14, 6, 4, 5, 7, 15, 13, 29, 31, 23, 21, 
  20, 22, 30, 28, 24, 26, 18, 16, 17, 19, 27, 25, 9, 11, 3, 1
};

static const uint8_t HILBERT_GRAY_RANK_5[32] = {
  0, 31, 1, 30, 7, 8, 6, 9, 3, 28, 2, 29, 4, 11, 5, 10, 
  23, 24, 22, 25, 16, 15, 17, 14, 20, 27, 21, 26, 19, 12, 18, 13
};

static const uint8_t HILBERT_CHILD_ENTRY_5[32] = {
  0, 0, 0, 3, 3, 0, 9, 10, 10, 9, 0, 3, 3, 0, 9, 10, 
  9, 9, 0, 3, 6, 5, 12, 15, 12, 12, 5, 6, 23, 17, 9, 3
};

static const uint8_t HILBERT_CHILD_DIR_5[32] = {
  1, 3, 0, 2, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 1, 
  1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 4, 3, 1
};

static const uint8_t HILBERT_GRAY_6[64] = {
  0, 2, 6, 4, 20, 22, 18, 16, 24, 26, 30, 28, 12, 8, 10, 14, 
  46, 42, 58, 62, 54, 50, 34, 38, 36, 52, 48, 32, 40, 44, 60, 56, 
  57, 49, 51, 59, 43, 35, 33, 41, 45, 37, 39, 47, 63, 55, 53, 61, 
  29, 13, 9, 25, 27, 11, 15, 31, 23, 7, 3, 19, 17, 21, 5, 1
};

static const uint8_t HILBERT_GRAY_RANK_6[64] = {
  0, 63, 1, 58, 3, 62, 2, 57, 13, 50, 14, 53, 12, 49, 15, 54, 
  7, 60, 6, 59, 4, 61, 5, 56, 8, 51, 9, 52, 11, 48, 10, 55, 
  27, 38, 22, 37, 24, 41, 23, 42, 28, 39, 17, 36, 29, 40, 16, 43, 
  26, 33, 21, 34, 25, 46, 20, 45, 31, 32, 18, 35, 30, 47, 19, 44
};

static const uint8_t HILBERT_CHILD_ENTRY_6[64] = {
  0, 0, 0, 3, 3, 0, 5, 6, 6, 5, 0, 3, 18, 23, 20, 17, 
  17, 20, 5, 0, 9, 12, 29, 24, 27, 10, 15, 30, 23, 18, 3, 6, 
  6, 15, 12, 5, 20, 29, 30, 23, 18, 27, 24, 17, 0, 9, 10, 3, 
  34, 51, 54, 39, 36, 53, 48, 33, 40, 57, 60, 45, 39, 33, 17, 5
};

static const uint8_t HILBERT_CHILD_DIR_6[64] = {
  1, 2, 0, 4, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 5, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1, 5, 4, 2
};

static const uint8_t HILBERT_GRAY_7[128] = {
  0, 8, 12, 4, 20, 28, 24, 16, 80, 88, 92, 84, 68, 76, 72, 64, 
  66, 2, 6, 70, 86, 22, 18, 82, 90, 26, 30, 94, 78, 74, 10, 14, 
  46, 110, 102, 38, 34, 42, 106, 98, 96, 104, 108, 100, 36, 32, 40, 44, 
  60, 56, 48, 52, 54, 50, 58, 62, 126, 124, 116, 118, 114, 112, 120, 122, 
  123, 59, 27, 91, 95, 127, 63, 31, 23, 87, 83, 19, 51, 55, 119, 115, 
  113, 81, 85, 117, 53, 21, 17, 49, 57, 25, 89, 121, 125, 93, 29, 61, 
  45, 47, 39, 37, 101, 109, 111, 103, 99, 35, 43, 107, 105, 41, 33, 97, 
  65, 69, 77, 73, 75, 79, 71, 67, 3, 11, 15, 7, 5, 13, 9, 1
};

static const uint8_t HILBERT_GRAY_RANK_7[128] = {
  0, 127, 17, 120, 3, 124, 18, 123, 1, 126, 30, 121, 2, 125, 31, 122, 
  7, 86, 22, 75, 4, 85, 21, 72, 6, 89, 25, 66, 5, 94, 26, 71, 
  45, 110, 36, 105, 44, 99, 35, 98, 46, 109, 37, 106, 47, 96, 32, 97, 
  50, 87, 53, 76, 51, 84, 52, 77, 49, 88, 54, 65, 48, 95, 55, 70, 
  15, 112, 16, 119, 12, 113, 19, 118, 14, 115, 29, 116, 13, 114, 28, 117, 
  8, 81, 23, 74, 11, 82, 20, 73, 9, 90, 24, 67, 10, 93, 27, 68, 
  40, 111, 39, 104, 43, 100, 34, 103, 41, 108, 38, 107, 42, 101, 33, 102, 
  61, 80, 60, 79, 58, 83, 59, 78, 62, 91, 63, 64, 57, 92, 56, 69
};

static const uint8_t HILBERT_CHILD_ENTRY_7[128] = {
  0, 0, 0, 9, 9, 0, 5, 12, 12, 5, 0, 9, 24, 17, 20, 29, 
  29, 92, 89, 24, 9, 72, 77, 12, 5, 68, 65, 0, 17, 20, 85, 80, 
  80, 17, 24, 89, 92, 85, 20, 29, 30, 23, 18, 27, 90, 95, 86, 83, 
  66, 71, 78, 75, 72, 77, 68, 65, 0, 3, 10, 9, 12, 15, 6, 5, 
  6, 71, 102, 39, 34, 3, 66, 99, 106, 43, 46, 111, 78, 75, 10, 15, 
  15, 46, 43, 10, 75, 106, 111, 78, 71, 102, 39, 6, 3, 34, 99, 66, 
  83, 80, 89, 90, 27, 18, 17, 24, 29, 92, 85, 20, 23, 86, 95, 30, 
  63, 58, 51, 54, 53, 48, 57, 60, 125, 116, 113, 105, 75, 65, 5, 9
};

static const uint8_t HILBERT_CHILD_DIR_7[128] = {
  3, 2, 0, 4, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 1, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5, 1, 6, 2, 3
};

static inline uint8_t hilbert_gray(uint32_t k, uint32_t w) {
  switch(k) {
    case 1: return HILBERT_GRAY_1[w];
    case 2: return HILBERT_GRAY_2[w];
    case 3: return HILBERT_GRAY_3[w];
    case 4: return HILBERT_GRAY_4[w];
    case 5: return HILBERT_GRAY_5[w];
    case 6: return HILBERT_GRAY_6[w];
    case 7: return HILBERT_GRAY_7[w];
    default: return 0;
  }
}

static inline uint8_t hilbert_gray_rank(uint32_t k, uint32_t g) {
  switch(k) {
    case 1: return HILBERT_GRAY_RANK_1[g];
    case 2: return HILBERT_GRAY_RANK_2[g];
    case 3: return HILBERT_GRAY_RANK_3[g];
    case 4: return HILBERT_GRAY_RANK_4[g];
    case 5: return HILBERT_GRAY_RANK_5[g];
    case 6: return HILBERT_GRAY_RANK_6[g];
    case 7: return HILBERT_GRAY_RANK_7[g];
    default: return 0;
  }
}

static inline uint8_t hilbert_child_entry(uint32_t k, uint32_t w) {
  switch(k) {
    case 1: return HILBERT_CHILD_ENTRY_1[w];
    case 2: return HILBERT_CHILD_ENTRY_2[w];
    case 3: return HILBERT_CHILD_ENTRY_3[w];
    case 4: return HILBERT_CHILD_ENTRY_4[w];
    case 5: return HILBERT_CHILD_ENTRY_5[w];
    case 6: return HILBERT_CHILD_ENTRY_6[w];
    case 7: return HILBERT_CHILD_ENTRY_7[w];
    default: return 0;
  }
}

static inline uint8_t hilbert_child_dir(uint32_t k, uint32_t w) {
  switch(k) {
    case 1: return HILBERT_CHILD_DIR_1[w];
    case 2: return HILBERT_CHILD_DIR_2[w];
    case 3: return HILBERT_CHILD_DIR_3[w];
    case 4: return HILBERT_CHILD_DIR_4[w];
    case 5: return HILBERT_CHILD_DIR_5[w];
    case 6: return HILBERT_CHILD_DIR_6[w];
    case 7: return HILBERT_CHILD_DIR_7[w];
    default: return 0;
  }
}

#ifdef __cplusplus
}
#endif
